[project]
name = "rag-pipeline-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.0",
]

[project.scripts]
rag-pipeline-poc = "rag_pipeline_poc:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
